on: 
  push:
    branches:
    - master
name: expo_deploy
jobs:
  expo_deploy:    
    name: Expo Build
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2
    
    - name: Check NPM
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: npm
    
    - uses: expo/expo-github-action@v7
      with:
        expo-version: latest
        eas-version: latest
        token: SH7CPpJ-Q4kIok9C0tA2ldb-qDBfwbyqi4punoxp
    
    - name: Install dependencies
      run: |
        npm install 
        npm install expo -y
        npm install expo-updates -y

    - name: 🚀 Publish app
      run: expo publish --non-interactive

    - name: expo Build
      run: |
          expo build:android -t apk --non-interactive  
   
